# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/logging.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/logging.proto\")\n\nLogRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"$\n\x10MessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2c\n\x0eLoggingService\x12\'\n\nLogMessage\x12\x0b.LogRequest\x1a\x0c.LogResponse\x12(\n\x0bGetMessages\x12\x06.Empty\x1a\x11.MessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=23
  _globals['_LOGREQUEST']._serialized_end=64
  _globals['_LOGRESPONSE']._serialized_start=66
  _globals['_LOGRESPONSE']._serialized_end=95
  _globals['_MESSAGESRESPONSE']._serialized_start=97
  _globals['_MESSAGESRESPONSE']._serialized_end=133
  _globals['_EMPTY']._serialized_start=135
  _globals['_EMPTY']._serialized_end=142
  _globals['_LOGGINGSERVICE']._serialized_start=144
  _globals['_LOGGINGSERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
